Feature/mock user service
COMPASS-DPG/wpcas-service pull request #12
Opened 2023-10-10 14:35 UTC by Ajay-Maury

2023-10-12 09:16 UTC, prashantesmagico requested changes

2023-10-12 09:16 UTC, prashantesmagico commented on src/mockModules/mock-level/mock-level.module.ts
> +  providers: [MockLevelService, PrismaService],
No need to import prisma service here as Globally prisma module is available.

2023-10-12 09:16 UTC, prashantesmagico commented on src/mockModules/mock-team/mock-team.module.ts
> +  providers: [MockTeamService, PrismaService],
No need to import prisma service here

2023-10-12 09:16 UTC, prashantesmagico commented on src/mockModules/mock-user/mock-user.module.ts
> +  providers: [MockUserService, PrismaService],
No need to import prisma service in this module

2023-10-13 05:35 UTC, VamshiBatta07 approved these changes

2023-10-13 05:38 UTC, prashantesmagico approved these changes

2023-10-13 07:46 UTC, merged