Response tracer APIs created
COMPASS-DPG/wpcas-service pull request #16
Opened 2023-10-11 07:33 UTC by Ajay-Maury

2023-10-11 09:09 UTC, VamshiBatta07 requested changes

2023-10-11 09:09 UTC, VamshiBatta07 commented on src/response-tracker/dto/create-response-tracker.dto.ts
> +  responseJson?: Record<string, any>;
Record<string, any>  ===>  Record<number, boolean>
 
number == questionId.
boolean == response to the question(Since the questions are just yes or no questions).

Edit: 
 Record<string, any>  ===>  Record<string, boolean>
 
 string == question.

2023-10-11 09:36 UTC, Ajay-Maury commented on src/response-tracker/dto/create-response-tracker.dto.ts
> +  responseJson?: Record<string, any>;
done

2023-10-11 14:23 UTC, VamshiBatta07 approved these changes

2023-10-12 10:05 UTC, prashantesmagico approved these changes

2023-10-12 10:05 UTC, prashantesmagico commented on src/response-tracker/response-tracker.controller.ts
> +  @ApiResponse({ status: HttpStatus.OK, type: ResponseTrackerDtoResponse })
use HttpStatus.CREATED in swagger ApiResponse

2023-10-13 07:52 UTC, merged