API for survey config and survey parameter
COMPASS-DPG/wpcas-service pull request #18
Opened 2023-10-11 14:00 UTC by prashantesmagico

2023-10-11 14:10 UTC, Ajay-Maury requested changes

2023-10-11 14:10 UTC, Ajay-Maury commented on src/survey-config/survey-config.controller.ts
> +      return res.status(HttpStatus.INTERNAL_SERVER_ERROR).json({
Use status code coming from getprismaerrorstatusandmessage function instead of Http Internal server status

2023-10-11 14:10 UTC, Ajay-Maury commented on src/survey-parameter/survey-parameter.controller.ts
> +      return res.status(HttpStatus.INTERNAL_SERVER_ERROR).json({
Use statuscode coming from getprismaerrorstatusandmessage function

2023-10-11 15:23 UTC, prashantesmagico commented on src/survey-parameter/survey-parameter.controller.ts
> +      return res.status(HttpStatus.INTERNAL_SERVER_ERROR).json({
Done

2023-10-11 15:23 UTC, prashantesmagico commented on src/survey-config/survey-config.controller.ts
> +      return res.status(HttpStatus.INTERNAL_SERVER_ERROR).json({
Done

2023-10-12 04:36 UTC, Ajay-Maury approved these changes

2023-10-13 04:17 UTC, VamshiBatta07 approved these changes

2023-10-13 08:04 UTC, merged