Created the crud APIs for the admin department
COMPASS-DPG/wpcas-service pull request #33
Opened 2023-10-18 12:37 UTC by prashantesmagico

2023-10-19 10:58 UTC, Ajay-Maury approved these changes

2023-10-20 05:36 UTC, VamshiBatta07 requested changes

2023-10-20 05:36 UTC, VamshiBatta07 commented on src/admin-department/admin-department.service.ts
- [ ] Please merge the create and update function to make a single createOrUpdateAdminDepartment function as discussed.

2023-10-26 08:59 UTC, prashantesmagico commented on src/admin-department/admin-department.service.ts
Made changes accordingly

2023-10-26 10:18 UTC, Ajay-Maury approved these changes

2023-10-26 10:20 UTC, VamshiBatta07 approved these changes
Please resolve the merge conflicts.
Then merge it.

2023-10-26 10:50 UTC, merged