Mock Designation APIs.
COMPASS-DPG/wpcas-service pull request #34
Opened 2023-10-18 12:45 UTC by VamshiBatta07

2023-10-18 13:49 UTC, prashantesmagico requested changes

2023-10-18 13:49 UTC, prashantesmagico commented on src/mockModules/mock-designation/mock-designation.controller.ts
> +  @Put(":id")
use patch instead of Put

2023-10-19 10:54 UTC, Ajay-Maury requested changes

2023-10-19 10:54 UTC, Ajay-Maury commented on src/mockModules/mock-designation/mock-designation.controller.ts
Add ApiOperation and ApiResponse  to all APIs for swagger (NIT)

2023-10-19 11:09 UTC, prashantesmagico approved these changes

2023-10-19 12:08 UTC, Ajay-Maury approved these changes

2023-10-19 12:17 UTC, merged