Feature/question bank template
COMPASS-DPG/wpcas-service pull request #70
Opened 2023-11-14 09:48 UTC by prashantesmagico

2023-11-14 10:01 UTC, VamshiBatta07 requested changes

2023-11-14 10:01 UTC, VamshiBatta07 commented on src/question-bank/question-bank.service.ts
> +    const header = ["competency", "competencyLevelNu", "question"];
Should be "competencyLevelNumber" instead of "competencyLevelNu".

2023-11-14 10:01 UTC, VamshiBatta07 commented on src/question-bank/question-bank.service.ts
Please the code for fetching competency and competencyLevelNumber if there is no question uploaded for them.

2023-11-15 06:19 UTC, prashantesmagico commented on src/question-bank/question-bank.service.ts
implemented

2023-11-15 07:03 UTC, VamshiBatta07 approved these changes

2023-11-15 07:04 UTC, merged